
import { ServicePrice, TrechoMapping, SupervisaoMapping } from '../types';

export const EQUIPMENT_CATEGORIES: Record<string, string> = {
  "EH": "Escavadeira Hidráulica",
  "CB": "Caminhão Basculante",
  "CBL": "Caminhão Basculante",
  "MN": "Motoniveladora",
  "PC": "Pá Carregadeira",
  "RE": "Retroescavadeira",
  "REL": "Retroescavadeira",
  "MEL": "Miniescavadeira",
  "VLL": "Veículo Leve",
  "CM": "Cavalo Mecânico"
};

export const TRECHO_MAPPINGS: TrechoMapping[] = [
    { "km_inicial": 0.001, "km_final": 16, "cidade": "Açailândia", "trecho": "T-01" },
    { "km_inicial": 16.001, "km_final": 44, "cidade": "S.F. Brejão", "trecho": "T-01" },
    { "km_inicial": 44.001, "km_final": 78, "cidade": "João Lisboa", "trecho": "T-01" },
    { "km_inicial": 78.001, "km_final": 96.397, "cidade": "Imperatriz", "trecho": "T-01" },
    { "km_inicial": 96.398, "km_final": 122.82, "cidade": "Edson Lobão", "trecho": "T-01" },
    { "km_inicial": 122.821, "km_final": 152.303, "cidade": "Ribamar Fiquene", "trecho": "T-01" },
    { "km_inicial": 152.304, "km_final": 172.403, "cidade": "Campestre", "trecho": "T-01" },
    { "km_inicial": 172.404, "km_final": 195, "cidade": "Porto Franco", "trecho": "T-01" },
    { "km_inicial": 195.1, "km_final": 213.603, "cidade": "Estreito", "trecho": "T-02" },
    { "km_inicial": 213.604, "km_final": 218.976, "cidade": "Aguiarnópolis", "trecho": "T-02" },
    { "km_inicial": 218.977, "km_final": 253.5, "cidade": "Palmeiras Do", "trecho": "T-02" },
    { "km_inicial": 253.501, "km_final": 274.15, "cidade": "Darcinópolis", "trecho": "T-02" },
    { "km_inicial": 274.151, "km_final": 299.999, "cidade": "Babaçulândia", "trecho": "T-02" },
    { "km_inicial": 300, "km_final": 300, "cidade": "São Luís", "trecho": "T-04" },
    { "km_inicial": 300.001, "km_final": 356.619, "cidade": "Babaçulândia", "trecho": "T-02" },
    { "km_inicial": 356.62, "km_final": 385.4, "cidade": "Araguaína", "trecho": "T-02" },
    { "km_inicial": 385.4, "km_final": 465.4, "cidade": "Palmeirante", "trecho": "T-02" },
    { "km_inicial": 465.401, "km_final": 520.455, "cidade": "Tupiratins", "trecho": "T-03" },
    { "km_inicial": 520.456, "km_final": 536.741, "cidade": "Guaraí", "trecho": "T-03" },
    { "km_inicial": 536.742, "km_final": 580.293, "cidade": "Tupirama", "trecho": "T-03" },
    { "km_inicial": 580.294, "km_final": 608.637, "cidade": "Rio Dos Bois", "trecho": "T-03" },
    { "km_inicial": 608.638, "km_final": 698.981, "cidade": "Miracema", "trecho": "T-03" },
    { "km_inicial": 608.638, "km_final": 698.981, "cidade": "Miracema", "trecho": "T-03" },
    { "km_inicial": 698.982, "km_final": 735.6, "cidade": "Porto Nacional", "trecho": "T-03" },
    { "km_inicial": 900, "km_final": 902, "cidade": "Eng. VLI", "trecho": "T-04" }
];

export const SUPERVISAO_MAPPINGS: SupervisaoMapping[] = [
    { "trecho": "T-01", "supervisao": "Imperatriz" },
    { "trecho": "T-02", "supervisao": "Araguaina" },
    { "trecho": "T-03", "supervisao": "Palmas" },
    { "trecho": "T-04", "supervisao": "São Luis" },
    { "trecho": "VLI", "supervisao": "VLI - 2015" }
];

const MOBRA_PRICES: ServicePrice[] = [
    { "item": "3.1", "codigo_sap": null, "descricao": "MOBILIZACAO INICIAL (MOBRA)", "unidade": "VB", "preco_unitario": null, "quantidade": 1, "valor_total": null, "category": "MOBRA" },
    { "item": "100", "codigo_sap": "S.VP-01477", "descricao": "MOBILIZAÇÃO DE RETROESCAVADEIRA C/ OPERADOR", "unidade": "VB", "preco_unitario": 963.41, "quantidade": 1, "valor_total": 919.25, "category": "MOBRA" },
    { "item": "110", "codigo_sap": "S.VP-01478", "descricao": "DESMOBILIZAÇÃO DE RETROESCAVADEIRA C/ OPERADOR", "unidade": "VB", "preco_unitario": 963.41, "quantidade": 1, "valor_total": 919.25, "category": "MOBRA" },
    { "item": "120", "codigo_sap": "S.VP-01395", "descricao": "HR PRODUTIVA RETROESCAVADEIRA C/OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 14832, "valor_total": 940348.80, "category": "MOBRA" },
    { "item": "130", "codigo_sap": "S.VP-01396", "descricao": "HR IMPRODUTIVA RETROESCAVADEIRA C/OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 4912, "valor_total": 311420.80, "category": "MOBRA" },
    { "item": "140", "codigo_sap": "S.VP-01397", "descricao": "MOBILIZAÇÃO PA CARREGADEIRA C/ OPERADOR", "unidade": "VB", "preco_unitario": 1045.98, "quantidade": 1, "valor_total": 1014.34, "category": "MOBRA" },
    { "item": "150", "codigo_sap": "S.VP-01398", "descricao": "DESMOBILIZAÇÃO DE PA CARREGADEIRA C/OPERADOR", "unidade": "VB", "preco_unitario": 1045.98, "quantidade": 1, "valor_total": 1014.34, "category": "MOBRA" },
    { "item": "160", "codigo_sap": "S.VP-01399", "descricao": "HORA PRODUTIVA PA CARREGADEIRA C/OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 10188, "valor_total": 645919.20, "category": "MOBRA" },
    { "item": "170", "codigo_sap": "S.VP-01400", "descricao": "HORA IMPRODUTIVA PA CARREGADEIRA C/OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 3006, "valor_total": 190580.40, "category": "MOBRA" },
    { "item": "180", "codigo_sap": "S.VP-01401", "descricao": "MOBILIZAÇÃO CAMINHÃO BASCULANTE - C/MOTORISTA", "unidade": "VB", "preco_unitario": 281.11, "quantidade": 2, "valor_total": 545.22, "category": "MOBRA" },
    { "item": "190", "codigo_sap": "S.VP-01402", "descricao": "DESMOBILIZAÇÃO CAMINHÃO BASCULANTE - C/MOTORISTA", "unidade": "VB", "preco_unitario": 281.11, "quantidade": 2, "valor_total": 545.22, "category": "MOBRA" },
    { "item": "200", "codigo_sap": "S.VP-01403", "descricao": "KM RODADO CAMINHÃO BASCULANTE - C/MOTORISTA", "unidade": "KM", "preco_unitario": 1.81, "quantidade": 648000, "valor_total": 1140480.00, "category": "MOBRA" },
    { "item": "210", "codigo_sap": "S.VP-01404", "descricao": "HORA IMPRODUTIVA BASCULANTE - C/MOTORISTA", "unidade": "H", "preco_unitario": 65.42, "quantidade": 2454, "valor_total": 155583.60, "category": "MOBRA" },
    { "item": "220", "codigo_sap": "S.VP-01405", "descricao": "MOBILIZAÇÃO DE CAMINHÃO PIPA C/MOTOTISTA", "unidade": "VB", "preco_unitario": 319.71, "quantidade": 9, "valor_total": 2795.85, "category": "MOBRA" },
    { "item": "230", "codigo_sap": "S.VP-01406", "descricao": "DESMOBILIZAÇÃO DE CAMINHÃO PIPA C/MOTOTISTA", "unidade": "VB", "preco_unitario": 319.71, "quantidade": 9, "valor_total": 2795.85, "category": "MOBRA" },
    { "item": "240", "codigo_sap": "S.VP-01407", "descricao": "HORA PRODUTIVA CAMINHÃO PIPA", "unidade": "H", "preco_unitario": 65.42, "quantidade": 590, "valor_total": 37406.00, "category": "MOBRA" },
    { "item": "250", "codigo_sap": "S.VP-01408", "descricao": "HORA IMPRODUTIVA CAMINHÃO PIPA C/ MOTORISTA", "unidade": "H", "preco_unitario": 65.42, "quantidade": 2985, "valor_total": 189249.00, "category": "MOBRA" },
    { "item": "260", "codigo_sap": "S.VP-01409", "descricao": "MOBILIZAÇÃO DE MOTONIVELADORA C/OPERADOR", "unidade": "VB", "preco_unitario": 1188.01, "quantidade": 2, "valor_total": 2284.76, "category": "MOBRA" },
    { "item": "270", "codigo_sap": "S.VP-01410", "descricao": "DESMOBILIZAÇÃO DE MOTONIVELADORA C/OPERADOR", "unidade": "VB", "preco_unitario": 1188.01, "quantidade": 2, "valor_total": 2284.76, "category": "MOBRA" },
    { "item": "280", "codigo_sap": "S.VP-01411", "descricao": "HORA PRODUTIVA MOTONIVELADORA C/OPERADOR", "unidade": "H", "preco_unitario": 87.27, "quantidade": 9040, "valor_total": 764964.80, "category": "MOBRA" },
    { "item": "290", "codigo_sap": "S.VP-01412", "descricao": "HORA IMPRODUTIVA MOTONIVELADORA C/OPERADOR", "unidade": "H", "preco_unitario": 87.27, "quantidade": 2749, "valor_total": 232620.38, "category": "MOBRA" },
    { "item": "3.25", "codigo_sap": "S.VP-01413", "descricao": "MOBILIZAÇÃO DE TRATOR ESTEIRA – C/OPERADOR", "unidade": "VB", "preco_unitario": 925.23, "quantidade": 1, "valor_total": 887.55, "category": "MOBRA" },
    { "item": "3.26", "codigo_sap": "S.VP-01414", "descricao": "DESMOBILIZAÇÃO DE TRATOR ESTEIRA – C/OPERADOR", "unidade": "VB", "preco_unitario": 925.23, "quantidade": 1, "valor_total": 887.55, "category": "MOBRA" },
    { "item": "3.27", "codigo_sap": "S.VP-01415", "descricao": "HORA PRODUTIVA TRATOR ESTEIRA – C/ OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 330, "valor_total": 20922.00, "category": "MOBRA" },
    { "item": "3.28", "codigo_sap": "S.VP-01416", "descricao": "HORA IMPRODUTIVA TRATOR ESTEIRA – C/ OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 270, "valor_total": 17118.00, "category": "MOBRA" },
    { "item": "380", "codigo_sap": "S.VP-01417", "descricao": "MOBILIZAÇÃO CARRETA PRANCHA - C/ MOTORISTA", "unidade": "VB", "preco_unitario": 785.33, "quantidade": 1, "valor_total": 761.58, "category": "MOBRA" },
    { "item": "390", "codigo_sap": "S.VP-01418", "descricao": "DESMOBILIZAÇÃO CARRETA PRANCHA - C/ MOTORISTA", "unidade": "VB", "preco_unitario": 785.33, "quantidade": 1, "valor_total": 761.58, "category": "MOBRA" },
    { "item": "400", "codigo_sap": "S.VP-01419", "descricao": "KM RODADO CARRETA PRANCHA - C/ MOTORISTA", "unidade": "KM", "preco_unitario": 2.50, "quantidade": 4008, "valor_total": 9699.36, "category": "MOBRA" },
    { "item": "410", "codigo_sap": "S.VP-01420", "descricao": "HORA IMPRODUTIVA CARRETA PRANCHA - C/ MOTORISTA", "unidade": "H", "preco_unitario": 87.27, "quantidade": 1023, "valor_total": 86566.26, "category": "MOBRA" },
    { "item": "460", "codigo_sap": "S.VP-01421", "descricao": "MOBILIZAÇÃO MINIESCAVADEIRA C/ OPERADOR", "unidade": "VB", "preco_unitario": 908.71, "quantidade": 1, "valor_total": 881.21, "category": "MOBRA" },
    { "item": "470", "codigo_sap": "S.VP-01422", "descricao": "DESMOBILIZAÇÃO MINIESCAVADEIRA C/ OPERADOR", "unidade": "VB", "preco_unitario": 908.70, "quantidade": 1, "valor_total": 881.21, "category": "MOBRA" },
    { "item": "480", "codigo_sap": "S.VP-01423", "descricao": "HORA PRODUTIVA MINIESCAVADEIRA HIDRAULICA C/ OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 4644, "valor_total": 294429.60, "category": "MOBRA" },
    { "item": "490", "codigo_sap": "S.VP-01424", "descricao": "HORA IMPRODUTIVA MINIESCAVADEIRA HIDRAULICA C/ OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 1584, "valor_total": 100425.60, "category": "MOBRA" },
    { "item": "500", "codigo_sap": "S.VP-01425", "descricao": "MOBILIZAÇÃO ESCAVADEIRA HIDRAULICA", "unidade": "VB", "preco_unitario": 1632.59, "quantidade": 1, "valor_total": 1583.21, "category": "MOBRA" },
    { "item": "510", "codigo_sap": "S.VP-01426", "descricao": "DESMOBILIZAÇÃO ESCAVADEIRA HIDRAULICA", "unidade": "VB", "preco_unitario": 1632.60, "quantidade": 1, "valor_total": 1583.21, "category": "MOBRA" },
    { "item": "520", "codigo_sap": "S.VP-01427", "descricao": "HORA PRODUTIVA ESCAVADEIRA HIDRAULICA", "unidade": "H", "preco_unitario": 65.42, "quantidade": 5850, "valor_total": 370890.00, "category": "MOBRA" },
    { "item": "530", "codigo_sap": "S.VP-01428", "descricao": "HORA IMPRODUTIVA ESCAVADEIRA HIDRAULICA", "unidade": "H", "preco_unitario": 65.42, "quantidade": 1950, "valor_total": 123630.00, "category": "MOBRA" },
    { "item": "3.41", "codigo_sap": "S.VP-01429", "descricao": "MOBILIZAÇÃO ROLO COMPACTADOR C/ OPERADOR", "unidade": "VB", "preco_unitario": 1013.30, "quantidade": 1, "valor_total": 982.65, "category": "MOBRA" },
    { "item": "3.42", "codigo_sap": "S.VP-01430", "descricao": "DESMOBILIZAÇÃO ROLO COMPACTADOR C/ OPERADOR", "unidade": "VB", "preco_unitario": 697.80, "quantidade": 1, "valor_total": 676.69, "category": "MOBRA" },
    { "item": "3.43", "codigo_sap": "S.VP-01431", "descricao": "HORA PRODUTIVA ROLO COMPACTADOR C/OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 930, "valor_total": 58962.00, "category": "MOBRA" },
    { "item": "3.44", "codigo_sap": "S.VP-01432", "descricao": "HORA IMPRODUTIVA ROLO COMPACTADOR C/OPERADOR", "unidade": "H", "preco_unitario": 65.42, "quantidade": 310, "valor_total": 19654.00, "category": "MOBRA" }
];

const RENTAL_PRICES: ServicePrice[] = [
    { "item": "3.1", "codigo_sap": "S.VP-00001", "descricao": "Mobilizacao Inicial (RENTAL)", "unidade": "VB", "preco_unitario": null, "quantidade": 1, "valor_total": null, "category": "RENTAL" },
    { "item": "100", "codigo_sap": "S.VP-01435", "descricao": "Mobilização De Retroescavadeira C/ Operador", "unidade": "VB", "preco_unitario": 1569.45, "quantidade": 1, "valor_total": 1569.45, "category": "RENTAL" },
    { "item": "110", "codigo_sap": "S.VP-01436", "descricao": "Desmobilização De Retroescavadeira C/ Operador", "unidade": "VB", "preco_unitario": 1569.45, "quantidade": 1, "valor_total": 1569.45, "category": "RENTAL" },
    { "item": "120", "codigo_sap": "S.VP-01437", "descricao": "Hr Produtiva Retroescavadeira C/Operador", "unidade": "H", "preco_unitario": 160.71, "quantidade": 14832, "valor_total": 2383650.72, "category": "RENTAL" },
    { "item": "130", "codigo_sap": "S.VP-01438", "descricao": "Hr Improdutiva Retroescavadeira C/Operador", "unidade": "H", "preco_unitario": 108.23, "quantidade": 4912, "valor_total": 531625.76, "category": "RENTAL" },
    { "item": "140", "codigo_sap": "S.VP-01439", "descricao": "Mobilização Pa Carregadeira C/ Operador", "unidade": "VB", "preco_unitario": 2319.45, "quantidade": 1, "valor_total": 2319.45, "category": "RENTAL" },
    { "item": "150", "codigo_sap": "S.VP-01440", "descricao": "Desmobilização De Pa Carregadeira C/Operador", "unidade": "VB", "preco_unitario": 2319.45, "quantidade": 1, "valor_total": 2319.45, "category": "RENTAL" },
    { "item": "160", "codigo_sap": "S.VP-01441", "descricao": "Hora Produtiva Pa Carregadeira C/Operador", "unidade": "H", "preco_unitario": 218.44, "quantidade": 10188, "valor_total": 2225466.72, "category": "RENTAL" },
    { "item": "170", "codigo_sap": "S.VP-01442", "descricao": "Hora Improdutiva Pa Carregadeira C/Operador", "unidade": "H", "preco_unitario": 144.96, "quantidade": 3006, "valor_total": 435749.76, "category": "RENTAL" },
    { "item": "180", "codigo_sap": "S.VP-01443", "descricao": "Mobilização Caminhão Basculante - C/Motorista", "unidade": "VB", "preco_unitario": 1137.96, "quantidade": 2, "valor_total": 2275.92, "category": "RENTAL" },
    { "item": "190", "codigo_sap": "S.VP-01444", "descricao": "Desmobilização Caminhão Basculante - C/Motorista", "unidade": "VB", "preco_unitario": 1137.96, "quantidade": 2, "valor_total": 2275.92, "category": "RENTAL" },
    { "item": "200", "codigo_sap": "S.VP-01445", "descricao": "Km Rodado Caminhão Basculante - C/Motorista", "unidade": "KM", "preco_unitario": 7.35, "quantidade": 648000, "valor_total": 4762800.00, "category": "RENTAL" },
    { "item": "210", "codigo_sap": "S.VP-01446", "descricao": "Hora Improdutiva Basculante - C/Motorista", "unidade": "H", "preco_unitario": 132.89, "quantidade": 2454, "valor_total": 326112.06, "category": "RENTAL" },
    { "item": "220", "codigo_sap": "S.VP-01447", "descricao": "Mobilização De Caminhão Pipa C/Mototista", "unidade": "VB", "preco_unitario": 1099.42, "quantidade": 9, "valor_total": 9894.78, "category": "RENTAL" },
    { "item": "230", "codigo_sap": "S.VP-01448", "descricao": "Desmobilização De Caminhão Pipa C/Mototista", "unidade": "VB", "preco_unitario": 1099.42, "quantidade": 9, "valor_total": 9894.78, "category": "RENTAL" },
    { "item": "240", "codigo_sap": "S.VP-01449", "descricao": "Hora Produtiva Caminhão Pipa", "unidade": "H", "preco_unitario": 185.82, "quantidade": 590, "valor_total": 109633.80, "category": "RENTAL" },
    { "item": "250", "codigo_sap": "S.VP-01450", "descricao": "Hora Improdutiva Caminhão Pipa C/ Motorista", "unidade": "H", "preco_unitario": 95.84, "quantidade": 2985, "valor_total": 286082.40, "category": "RENTAL" },
    { "item": "260", "codigo_sap": "S.VP-01451", "descricao": "Mobilização De Motoniveladora C/Operador", "unidade": "VB", "preco_unitario": 2609.38, "quantidade": 2, "valor_total": 5218.76, "category": "RENTAL" },
    { "item": "270", "codigo_sap": "S.VP-01452", "descricao": "Desmobilização De Motoniveladora C/Operador", "unidade": "VB", "preco_unitario": 2609.38, "quantidade": 2, "valor_total": 5218.76, "category": "RENTAL" },
    { "item": "280", "codigo_sap": "S.VP-01453", "descricao": "Hora Produtiva Motoniveladora C/Operador", "unidade": "H", "preco_unitario": 279.00, "quantidade": 9040, "valor_total": 2522160.00, "category": "RENTAL" },
    { "item": "290", "codigo_sap": "S.VP-01454", "descricao": "Hora Improdutiva Motoniveladora C/Operador", "unidade": "H", "preco_unitario": 193.29, "quantidade": 2749, "valor_total": 531354.21, "category": "RENTAL" },
    { "item": "3.25", "codigo_sap": "S.VP-01455", "descricao": "Mobilização De Trator Esteira – C/Operador", "unidade": "VB", "preco_unitario": 2525.62, "quantidade": 1, "valor_total": 2525.62, "category": "RENTAL" },
    { "item": "3.26", "codigo_sap": "S.VP-01456", "descricao": "Desmobilização De Trator Esteira – C/Operador", "unidade": "VB", "preco_unitario": 2525.62, "quantidade": 1, "valor_total": 2525.62, "category": "RENTAL" },
    { "item": "3.27", "codigo_sap": "S.VP-01457", "descricao": "Hora Produtiva Trator Esteira – C/ Operador", "unidade": "H", "preco_unitario": 326.34, "quantidade": 330, "valor_total": 107692.20, "category": "RENTAL" },
    { "item": "3.28", "codigo_sap": "S.VP-01458", "descricao": "Hora Improdutiva Trator Esteira – C/ Operador", "unidade": "H", "preco_unitario": 180.41, "quantidade": 270, "valor_total": 48710.70, "category": "RENTAL" },
    { "item": "380", "codigo_sap": "S.VP-01459", "descricao": "Mobilização Carreta Prancha - C/ Motorista", "unidade": "VB", "preco_unitario": 2236.74, "quantidade": 1, "valor_total": 2236.74, "category": "RENTAL" },
    { "item": "390", "codigo_sap": "S.VP-01460", "descricao": "Desmobilização Carreta Prancha - C/ Motorista", "unidade": "VB", "preco_unitario": 2236.74, "quantidade": 1, "valor_total": 2236.74, "category": "RENTAL" },
    { "item": "400", "codigo_sap": "S.VP-01461", "descricao": "Km Rodado Carreta Prancha - C/ Motorista", "unidade": "KM", "preco_unitario": 7.10, "quantidade": 4008, "valor_total": 28456.80, "category": "RENTAL" },
    { "item": "410", "codigo_sap": "S.VP-01462", "descricao": "Hora Improdutiva Carreta Prancha - C/ Motorista", "unidade": "H", "preco_unitario": 112.76, "quantidade": 1023, "valor_total": 115353.48, "category": "RENTAL" },
    { "item": "460", "codigo_sap": "S.VP-01463", "descricao": "Mobilização Miniescavadeira C/ Operador", "unidade": "VB", "preco_unitario": 1455.25, "quantidade": 1, "valor_total": 1455.25, "category": "RENTAL" },
    { "item": "470", "codigo_sap": "S.VP-01464", "descricao": "Desmobilização Miniescavadeira C/ Operador", "unidade": "VB", "preco_unitario": 1455.25, "quantidade": 1, "valor_total": 1455.25, "category": "RENTAL" },
    { "item": "480", "codigo_sap": "S.VP-01465", "descricao": "Hora Produtiva Miniescavadeira Hidraulica C/ Operador", "unidade": "H", "preco_unitario": 138.38, "quantidade": 4644, "valor_total": 642636.72, "category": "RENTAL" },
    { "item": "490", "codigo_sap": "S.VP-01466", "descricao": "Hora Improdutiva Miniescavadeira Hidraulica C/ Operador", "unidade": "H", "preco_unitario": 104.71, "quantidade": 1584, "valor_total": 165860.64, "category": "RENTAL" },
    { "item": "500", "codigo_sap": "S.VP-01467", "descricao": "Mobilização Escavadeira Hidraulica", "unidade": "VB", "preco_unitario": 4625.90, "quantidade": 1, "valor_total": 4625.90, "category": "RENTAL" },
    { "item": "510", "codigo_sap": "S.VP-01468", "descricao": "Desmobilização Escavadeira Hidraulica", "unidade": "VB", "preco_unitario": 4625.90, "quantidade": 1, "valor_total": 4625.90, "category": "RENTAL" },
    { "item": "520", "codigo_sap": "S.VP-01469", "descricao": "Hora Produtiva Escavadeira Hidraulica", "unidade": "H", "preco_unitario": 283.19, "quantidade": 5850, "valor_total": 1656661.50, "category": "RENTAL" },
    { "item": "530", "codigo_sap": "S.VP-01470", "descricao": "Hora Improdutiva Escavadeira Hidraulica", "unidade": "H", "preco_unitario": 185.23, "quantidade": 1950, "valor_total": 361198.50, "category": "RENTAL" },
    { "item": "3.41", "codigo_sap": "S.VP-01471", "descricao": "Mobilização Rolo Compactador C/ Operador", "unidade": "VB", "preco_unitario": 1872.58, "quantidade": 1, "valor_total": 1872.58, "category": "RENTAL" },
    { "item": "3.42", "codigo_sap": "S.VP-01472", "descricao": "Desmobilização Rolo Compactador C/ Operador", "unidade": "VB", "preco_unitario": 1590.13, "quantidade": 1, "valor_total": 1590.13, "category": "RENTAL" },
    { "item": "3.43", "codigo_sap": "S.VP-01473", "descricao": "Hora Produtiva Rolo Compactador C/Operador", "unidade": "H", "preco_unitario": 163.66, "quantidade": 930, "valor_total": 152203.80, "category": "RENTAL" },
    { "item": "3.44", "codigo_sap": "S.VP-01474", "descricao": "Hora Improdutiva Rolo Compactador C/Operador", "unidade": "H", "preco_unitario": 120.81, "quantidade": 310, "valor_total": 37451.10, "category": "RENTAL" }
];

export const DEFAULT_SERVICE_PRICES: ServicePrice[] = [...MOBRA_PRICES, ...RENTAL_PRICES];
